### ISSUE TITLE
[Requirements] Device Discovery should be optional

### ISSUE THREAD

**Issue by dajiaji** [httpslocal/usecases#32]
I think device discovery functionality is an optional feature but it looks mandatory in [the current draft](https://httpslocal.github.io/usecases/).

**Comment by tomoyukilabs** [comment]
@dajiaji The current draft mandates *capability* of device discovery, but *exposing interfaces for discovery* is not explicitly mentioned. Therefor, we need to explicitly state that the UA should prevent web apps from enumerating home network devices. (I'm not sure whether it should be mentioned in the functional requirements or privacy and security, though.) WDYT?

**Comment by tomoyukilabs** [comment]
More specifically, what we need here is to mandate host name resolution in home network. However, such an approach is usually tied to service discovery mechanism like DNS-SD. Consequently, device discovery might be mandatory though discovery itself is not needed.

**Comment by dajiaji** [comment]
> (I'm not sure whether it should be mentioned in the functional requirements or privacy and security, though.) WDYT?

I'm not sure but it looks non-functional privacy requirement to me. Now I'm preparing a PR for privacy requirements. so Please wait for a while and check it.

> More specifically, what we need here is to mandate host name resolution in home network. However, such an approach is usually tied to service discovery mechanism like DNS-SD.

IMHO, we should assume the use case that a web service, which accesses a device in local network via a UA, knows the device URL in advance. Especially in case that the device URL is a public domain name (e.g., https://someprinter.somemanufacturer.com), I think there is no need to use the service discovery mechanism. What's your take on this?

**Comment by tomoyukilabs** [comment]
Okay, now I can agree that we don't need to limit name resolution to discovery-based host names like `.local`. In other words, the requirement of device discovery should be replaced with that of name resolution.

@dajiaji Could you include this change in your PR?

**Comment by dajiaji** [comment]
okay. I'll include the change.

**Comment by tomoyukilabs** [comment]
Closed via #34.
